name: promql
version: 0.0.0
synopsis: PromQL as a type rather than as text
category: Monitoring
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Widentities
- -Wredundant-constraints
- -Wcpp-undef
- -Wunused-packages

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - validity
  - validity-text
